//package imports
import Head from "next/head";
import { Inter } from "next/font/google";
//gloab css
import styles from "@/styles/Home.module.css";
// component imprts
// import Login from "@/src/components/login";
import Login from "../components/login";
// font inter
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <Login />
      </main>
    </>
  );
}
